### ISSUE TITLE
Accept ZDOTDIR when installing

### ISSUE THREAD

**Issue by DitchComfort** [teaxyz/setup#102]
tea should add the magic path/one-liner to the correct file when $ZDOTDIR is set.
I always end up with an additional .zshrc file in the $HOME directory when installing, instead it should add the one-liner to e.g. $HOME/.config/zsh/.zshrc

![image](https://user-images.githubusercontent.com/77794110/206262937-5c886bce-a3fc-46c0-9b6d-694b88724872.jpeg)

**Comment by DitchComfort** [comment]
I know...

**Comment by mxcl** [comment]
@DitchComfort we tend to just dump our thoughts here, no offense was meant.

Though is this POSIX compliant @jhheider?

**Comment by DitchComfort** [comment]
👍🏻

**Comment by mxcl** [comment]
This is done.

**Comment by DitchComfort** [comment]
Amazing 👍🏻
