### ISSUE TITLE
Installing tea in 2 places doesn't work

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/setup#105]
- I set TEA_PREFIX and installed it.
- I created a symlink to the cli and that symlink is in the PATH.
- I decided to install tea in a second location (~/.tea) so I set TEA_PREFIX to /Users/james/.tea.
- I tried to install tea.

```
sh <(curl https://tea.xyz)
error: not-found: pantry (spilt-tea-005)
no pantry at path: /Users/james/.tea/tea.xyz/var/pantry/projects, try `tea --sync`
```

- I removed the tea symlink and tried again and it worked.

**Comment by mxcl** [comment]
I just tried this:

```sh
TEA_PREFIX=$HOME/foo sh <(curl tea.xyz)
```

And it installed to the specified location just fine.

Then:

```sh
TEA_PREFIX=$HOME/foo tea +zlib.net
```

Installed lib to this prefix. So, seems to work fine to me. I imagine there's some disconnect here between how you expect it to behave and how it behaves, any clues?

**Comment by mxcl** [comment]
The error suggests your first tea installation is not installed properly, ie. it didn’t create the pantries. We could mitigate this by making the installer do `--sync` before running any existing tea installation, and maybe we should.

How did you install your first tea installation?

**Comment by magnusviri** [comment]
This produces the error.

```
TEA_PREFIX=$HOME/foo1 sh <(curl tea.xyz)
sudo ln -s $HOME/foo1/tea.xyz/v\*/bin/tea /usr/local/bin
TEA_PREFIX=$HOME/foo2 sh <(curl tea.xyz)
```

**Comment by mxcl** [comment]
does `tea --sync` not fix it?

**Comment by mxcl** [comment]
Probably would help if you told us platform information.

**Comment by magnusviri** [comment]
Sorry, macOS 12. `tea  --sync` doesn't work but `TEA_PREFIX=$HOME/foo2 tea  --sync` does.

I tracked this down and I kind of brought this on myself. The symlink feature I requested and helped with is causing this. Basically, curl and gum are symlinks to tea. Normally, TEA_PREFIX doesn't matter. But if I change TEA_PREFIX then curl and gum break.

I don't know if this is something you want to fix because it is getting kind of complicated. If you were going to fix it, I think you'd have to change some logic somewhere. I think you'd have to ignore TEA_PREFIX if it's a symlink and look for the patnry relative to tea.

**Comment by jhheider** [comment]
This is an interesting question. Obviously, you can magically be even more magical, and follow the symlinked `tea` backwards to "fake" a `TEA_PREFIX`, if you don't find the things you need in the explicit `TEA_PREFIX`. That's certainly magical, but it feels like a mistake to override an explicit setting with a derived one. The counter argument, which I find somewhat convincing, is that _if_ you've symlinked a tea symlink/binary, then you'd put a flag in the stand as to which `TEA_PREFIX` you _intend_ to be operating under.

I think both doing nothing and trying to follow the symlink run the risk of edge cases like this. I'm trying to decide what I expect to happen, if we follow the symlink, with the following:

```sh
TEA_PREFIX=foo YES=1 sh <(curl tea.xyz)
sudo ln -s tea /usr/local/bin/curl
TEA_PREFIX=foo2 YES=1 sh <(curl tea.xyz) # assume we use symlink-following magic
TEA_PREFIX=foo2 tea +crates.io/bat (curl tea.xyz | bat)
```

You'll end with venvs in two different prefixes, maybe. Or something will break.

**Comment by magnusviri** [comment]
Since it's just curl and gum, in hstall.sh you could just check to see if they're symlinks to tea and if they are, don't run them but pick the next one in line. This is sounding like checken and egg syndrome. And yes, I'm not just an edge case, I'm an agent of Chaos. LOL.

Python always finds it's libs relative to the binary. I guess that's what I expect tea to do. And this could be an issue because, although I am not sure anyone would really do this, but it has occurred to me that if I wanted multiple versions of python that were the same version number, I'd have to have multiple installations of tea. And if I did that, each Python would basically be it's own virtual environment that would have it's own libraries installed. I wouldn't do that, it's messy. I'm just saying that tea enables something that wasn't possible before, which is to virtualize "global" installs. This applies to node also. Again, I'm not saying it's a good idea, it's just possible.

Oh, and the reason it matters is because if someone had multiple tea's then they might bump into this bug, if they have the symlinks like I do. And I know you guys are working on tea/cmd and that's where the hypothetical installer will go. I've felt a little bit of nudging that you want the community to write the installer, instead of tea inc. I'm not sure if I'm that great of a coder but I am thinking of the issues and dealing with these symlinks is probably going to be the hardest task of the installer.

**Comment by magnusviri** [comment]
LOL. My brain just went crazy with tons of ideas for the installer. Where would I discuss that? teaxyz/cmd? Discussions aren't enabled there. If it's going to be a community thing, there should probably be discussions somewhere. Unless you guys want to write it! ;)

**Comment by mxcl** [comment]
oh ok, we need to indeed check that `gum` and `curl` are not symlinks to `tea`.

> My brain just went crazy with tons of ideas for the installer. Where would I discuss that? teaxyz/cmd?

I was trying to consolidate discussions in one place, but maybe that was dumb. I'll open them here.

**Comment by mxcl** [comment]
> The counter argument, which I find somewhat convincing, is that if you've symlinked a tea symlink/binary, then you'd put a flag in the stand as to which TEA_PREFIX you intend to be operating under.

This is also just works. So probs we should consider it.

**Comment by mxcl** [comment]
Scanning forward for an alternative to curl if curl is a symlink to tea is pretty involved. We can work around it for gum but not if curl is a symlink to tea.

I do wonder what the actual error is, maybe there's another way around this.

**Comment by mxcl** [comment]
k I get it, it's because `TEA_PREFIX` effects the underlying `tea`.

**Comment by mxcl** [comment]
Ideally we’d `sh <(curl tea.xyz) --prefix foo` but since our installer passes args through to the installed `tea` this makes our behavior inconsistent.

I guess we can process `--prefix` and `--version` only tho.
