### ISSUE TITLE
New linux reqs script fails if sudo is not available

### ISSUE THREAD

**Issue by jhheider** [teaxyz/setup#109]
https://github.com/teaxyz/pantry.extra/actions/runs/3754256354/jobs/6378322983

**Comment by jhheider** [comment]
```javascript
  if (os.platform() != 'darwin') {
    const sh = path.join(path.dirname(__filename), "install-pre-reqs.sh")
    if (process.getuid() == 0) {
      execSync(sh)
    } else {
      execSync(`sudo ${sh}`)
    }
  }
```

I think this might be a bug in teaxyz/infuser (we should install and configure sudo in the infuser), as I consider it.

**Comment by mxcl** [comment]
`sudo` is called in `action.js`:

```js
    const sh = path.join(path.dirname(__filename), "install-pre-reqs.sh")
    if (process.getuid() == 0) {
      execSync(sh)
    } else {
      execSync(`sudo ${sh}`)
    }
```

So basically you are saying that infuser both has no `sudo` AND isn’t running as root? What do you propose we do? Will `apt-get install` even work?

**Comment by jhheider** [comment]
No, not as it stands. I believe we need to add and configure sudo in infuser for this.

**Comment by jhheider** [comment]
Fixed: https://github.com/teaxyz/infuser/commit/12680b217ca09fad54e0582467ccb3225dece725
