### ISSUE TITLE
gum_no_tty not working

### ISSUE THREAD

**Issue by jhheider** [teaxyz/setup#114]
It looks like ba211f52deb1e0ca844681e32e209f2585fd6a1b removed a `test ! -t 1` variant of gum confirm, which breaks the docker build: https://github.com/teaxyz/infuser/actions/runs/3763585836

**Comment by jhheider** [comment]
Actually, the major issue is renaming of YES > TEA_YES. Easy fix in infuser; PR'd a better test/error message to help others.

**Comment by mxcl** [comment]
Sorry for the thoughtless rename. It might not even have been a good idea (depends if `YES` is standardized or not).
