### ISSUE TITLE
Trigger CI here after tea/cli is released

### ISSUE THREAD

**Issue by mxcl** [teaxyz/setup#122]
So we can verify the installer and action work with the latest release.

Potentially getting us ahead of any breakage.

**Comment by jhheider** [comment]
Can certainly trigger it from teaxyz/cli via workflow_dispatch. One question is whether we should wait-fail on it. That'd make the release look failed, even if only CI here failed. dispatch-and-forget is even easier. I'll see about the first, first, using `aurelien-baudet/workflow-dispatch@v2` (probably), and we can set `wait-for-completion: false` if desired.

**Comment by mxcl** [comment]
> dispatch-and-forget is even easier

that's fine. Though we want a slack notification. I added deets in the PR.
