### ISSUE TITLE
install curl and tar if necessary

### ISSUE THREAD

**Issue by mxcl** [teaxyz/setup#40]
like, we can, so we should.

In theory they may have downloaded the installer without curl, though it is more likely they have no tar for some reason

**Comment by jhheider** [comment]
It always mystified me that curl wasn't part of more base systems. But I've rarely seen a UNIX-like without tar, fortunately.

**Comment by mxcl** [comment]
yeah this aint a big priority. It's a getting to five-nines kind of task.

**Comment by mxcl** [comment]
lol, we can't untar the tarball for tar without tar.

So, we could be amazing and handle exotic cases (eg. base bones docker) by
* providing the tea binary un-tar’d, uncompressed
* we still need cURL, but don’t need tar or gzip-utils

Is it worth it? Perhaps.

**Comment by jhheider** [comment]
Is there a native tar handler for Deno? Providing a raw deno binary could get us everything, since it's a programming language in a single file.
