### ISSUE TITLE
Minimum macOS11 Support Check

### ISSUE THREAD

**Issue by Xercesblu3** [teaxyz/setup#44]
our minimum is macOS 11, so we must check for that and error if problem
@tea/setup graceful error if no tar installed

**Comment by Xercesblu3** [comment]
@mxcl need a bit more detail please. Notes from @jhheider on this: _"check when compiling things? installing bottles? installing the cli?"_

**Comment by Xercesblu3** [comment]
@MarcosJCarbonell this one is a priority to get completed before launch please

**Comment by mxcl** [comment]
yeah when installing tea, this is indeed thus the correct repo.
