### ISSUE TITLE
bug: tea 0.8.6 has missing keys  

### ISSUE THREAD

**Issue by getneil** [teaxyz/setup#46]
Error:
```
Error: Error building site: "/home/runner/work/www/www/src/content/packages/darwinsys_com_file.md:2:1": failed to unmarshal YAML: yaml: line 2: did not find expected key
```

Source: https://github.com/teaxyz/www/actions/runs/3285301428/jobs/5414658470

**Comment by getneil** [comment]
problem is with the markdown file generated. sorry

**Comment by mxcl** [comment]
nps, this is a sign we need to make the error output clearer
