### ISSUE TITLE
Doesn't work in fish

### ISSUE THREAD

**Issue by gilbertwong96** [teaxyz/setup#5]
Hi, Max.

My default shell is [fish](http://fishshell.com/). The setup command `sh <(curl tea.xyz) ci` doesn't work in my environment. Maybe we need a better way to make a transmission layer.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/20479699/171136714-d11fdedb-c13d-449e-8264-0c4b8fda4a9b.png">

I read the shell downloaded from [tea.xyz](https://tea.xyz). Is `zsh` the recommended way?

**Comment by mxcl** [comment]
Yeah we'll need to think this through for other shells for sure, however currently we only support zsh.

Obv. this is unacceptable, but we're still new (for now).

**Comment by mxcl** [comment]
@jhheider you know fish, what we gunna do

**Comment by jhheider** [comment]
Hm, based on my reading, the rather ugly fish translation of the above is:

```shell
sh (curl tea.xyz|psub) -- ci
```

That's not gonna win any awards.

**Comment by mxcl** [comment]
```sh
curl foo | sh -s -- bar
```

I think is generalized though unpleasant.

**Comment by mxcl** [comment]
We have documented the fish usage at `tea/cli`
