### ISSUE TITLE
prefer `.tar.xz` downloads if the system tar can decompress them

### ISSUE THREAD

**Issue by mxcl** [teaxyz/setup#54]
The tricky part here is determining if `tar` supports this format.

On mac the answer is easy: yes.

On other platforms, we need a test.

> We want to prefer `.tar.xz` so we download faster, tea is unfortunately large due to `deno` and this is not ideal for users with less available bandwidth

**Comment by jhheider** [comment]
a compressed single empty file is 148B as tar.gz.

base64: 

`/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4AX/AFNdADMb7AG6cMNAaNMVK8FvZMaza8QKKTQY6wZ3kG/F814lHE9ruhkFO5DAG7XNamN7JMHavgmbbLacr72NaAzgGUXOstqUaGb6kbp7jrkF+3aQT12CAAB8Uikc1gG8RwABb4AMAAAAeGbHwbHEZ/sCAAAAAARZWg==`

uuencode: 

```uuencode
begin 644 foo.tar.xz
M_3=Z6%H```3FUK1&`@`A`18```!T+^6CX`7_`%-=`#,;[`&Z<,-`:-,5*\%O
M9,:S:\0**308ZP9WD&_%\UXE'$]KNAD%.Y#`&[7-:F-[),':O@F;;+:<K[V-
M:`S@&47.LMJ4:&;ZD;I[CKD%^W:03UV"``!\4BD<U@&\1P`!;X`,````>&;'
-P;'$9_L"``````196@``
`
end
```

If you're willing to gamble (and test) that all supported systems have one of those, you can embedded the foo.tar.xz in the shell script; otherwise, you can `curl` a 148B file (though you incur the time cost of the curl.

**Comment by mxcl** [comment]
nice idea!
