### ISSUE TITLE
`Failed to get latest tea version`

### ISSUE THREAD

**Issue by mxcl** [teaxyz/setup#72]
this line:

```sh
v="$(gum spin --show-output --title 'determing tea version' -- $CURL "https://dist.tea.xyz/tea.xyz/$MIDFIX/versions.txt" | tail -n1)"
```

seems to fail in the script, but is fine if I run it at the terminal prompt.

error: `failed to get latest tea version`

which we print ourselves if `v` is empty. I don’t get it.

Also it doesn't *always* fail. But when it starts failing it seems to be stuck failed.

**Comment by jhheider** [comment]
Intermittent GHA network failures? Could always hard-code a fallback if we have versions we _really_ liked, just in case.

**Comment by mxcl** [comment]
> Could always hard-code a fallback if we have versions we really liked, just in case.

Pretty good idea TBH.

Possibly the installer should be hardcoded for the latest version including the GPG signature and SHA… is that good?

**Comment by jhheider** [comment]
I can't decide if that improves or weakens our security posture. Lots of ways to do it, though.

**Comment by mxcl** [comment]
K, so we hard code the fall back? Presumably that's the best of both worlds

**Comment by mxcl** [comment]
Fixed I believe
