### ISSUE TITLE
sudo: command not found

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/setup#75]
Many docker containers don't come with sudo. I'm also using [UTM](https://mac.getutm.app/) to run Linux and their ArchLinux image is missing sudo (it's running as root!). I can install sudo, but I thought I'd mention it. Maybe setup could check for sudo before trying to run it.

**Comment by mxcl** [comment]
Too true. We should:

1. check if `sudo` is there
2. check if we even need sudo (we might be already running as root)
