### ISSUE TITLE
Naming conflict with gitea cli client

### ISSUE THREAD

**Issue by jedahan** [teaxyz/setup#87]
When installing tea i got cryptic error messages like `Error: flag provided but not defined: -prefix`.
Turns out, I already had a `tea` cli for Gitea https://gitea.com/gitea/tea#the-official-cli-for-gitea .

This would also be the case for any function or alias named `tea`.

That's fine, but the install script should be able to handle this, at least during installation. Usually that means escaping the function call in the install script `\tea`, or hardcoding paths to the binary, etc.

A simpler and less error prone but less magic install script would just bail if `tea` exists. zsh example:

    (( $+commands[tea] )) && fail "command tea already found..."

**Comment by mxcl** [comment]
yes, refs https://github.com/teaxyz/cli/issues/179

We have this as a WIP: https://github.com/teaxyz/setup/pull/85

My plan is to offer to create `teaxyz` as the symlink if gitea is installed since they were here first. But we won't at this point be renaming ourselves in general.

**Comment by mxcl** [comment]
> This would also be the case for any function or alias named tea.

ahh, yes we better handle that too. Thank you.

**Comment by mxcl** [comment]
The bug is fixed. We still don't offer to name ourselves `teaxyz` but we'll get to that.

While working on this I noticed that generally linux distros install gitea as `gitea` and not `tea` so really this only effects `brew`.
