### ISSUE TITLE
Linking to ~/.local/bin instead of /usr/local/bin

### ISSUE THREAD

**Issue by tiziodcaio** [teaxyz/setup#97]
I would like to use this path, at least the possibility to customize

**Comment by mxcl** [comment]
we now don’t use /usr/local/bin by default instead using our shell magic to add us into the path if required.

Additionally, if we detect that you already put a working tea in PATH, we don’t add it.

If the user chooses no magic it still prompts for `/usr/local/bin`. If you would still like that to instead be a choice then pls reopen.
